name: Add Template Remote
on:
  create:

jobs:
  add-remote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git remote add landing-template https://github.com/spenpo-landing/landing-template
