name: Update
on: workflow_dispatch

jobs:
  update:
    if: ${{ github.event.repository.name != 'landing-template' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git remote update
          git merge --allow-unrelated-histories landing-template/main -X theirs
          git push
  skip:
    if: ${{ github.event.repository.name == 'landing-template' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'skipped for template repository'
